### ISSUE TITLE
pheat_save %>% print does not work with knitted Rmd output

### ISSUE THREAD

**Issue by scottdaniel** [kylebittinger/pheatbuilder#1]
Running something like this:
```
my_df_wide %>%
  pheat() %>%
  pheat_cluster_cols() %>%
  pheat_cluster_rows() %>%
  pheat_save(filename = here("Output", heatmap_name), width = 8, height = 8) %>%
  print()
```
in an interactive session saves the graph as well as prints it to the markdown sheet.

However, when knitting the code using `rmarkdown::render()` or the Knit button in Rstudio the pdf fails to show the graph in the resulting pdf or html. It only saves the individual pdf.

**Comment by scottdaniel** [comment]
Althought it should not make a difference, I also tried it with a numeric matrix instead of a data frame and still had the same problem.

**Comment by kylebittinger** [comment]
I have no idea why this is not working, but here is a workaround. The `pheat_save()` function returns the `pheat` object invisibly. First, you assign the `pheat` object to a variable:

```
ph <- my_df_wide %>%
  pheat() %>%
  pheat_cluster_cols() %>%
  pheat_cluster_rows() %>%
  pheat_save(filename = here("Output", heatmap_name), width = 8, height = 8)
```

Then, you can print the `pheat` object, but **you must print in a different code block** for some reason. Your next block can be as simple as:

```
ph
```

And the plot should be printed in your knitted document.

I have some ideas about why this is not working, and all of them make me pessimistic that it will be simple to properly fix this issue.
